FROM node:24.14.0-alpine3.21 AS build


WORKDIR /opt/app

RUN apk add --no-cache libc6-compat

COPY --from=build /opt/app /opt/app
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    chown -R node:node /opt/app /usr/local/bin/docker-entrypoint.sh

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=1337

USER node

EXPOSE 1337

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "run", "start"]
