export default {
  routes: [
    {
      method: 'POST',
      path: '/otp/send',
      handler: 'otp.send',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/check-phone',
      handler: 'otp.checkPhone',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/otp/check-phone',
      handler: 'otp.checkPhone',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/otp/verify',
      handler: 'otp.verify',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/register',
      handler: 'registration.register',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/check-cin',
      handler: 'registration.checkCin',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/check-email',
      handler: 'registration.checkEmail',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/check-referral',
      handler: 'registration.checkReferralCode',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/otp/login',
      handler: 'otp.login',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/logout',
      handler: 'session.logout',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/catalogue',
      handler: 'catalogue.list',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/profile/me',
      handler: 'profile.me',
      config: { auth: false },
    },
    {
      method: 'PUT',
      path: '/profile/me',
      handler: 'profile.updateMe',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/profile/referral',
      handler: 'profile.applyReferralCode',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/gains/overview',
      handler: 'gains.overview',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/gains/claim',
      handler: 'gains.claim',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/ranking/weekly',
      handler: 'ranking.weekly',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/ranking/stream',
      handler: 'ranking.stream',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/vidange/metadata',
      handler: 'vidange.metadata',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/vidange/consume',
      handler: 'vidange.consume',
      config: { auth: false },
    },
  ],
};
